# Generated by Django 3.1.1 on 2020-12-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restfullapp', '0002_auto_20201223_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
